[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sak"
version = "0.1.0"
description = "A Python utility package"
requires-python = ">=3.7"
authors = [
{name = "akhilsathuluri@tum.de"}
]

[tool.setuptools]
packages = ["sak"]

